"item:bus":
  model:
    item-model: minecraft:diamond_ore
  sounds:
    break:
      name:
      volume:
      pitch:
    place:
      name:
      volume:
      pitch:
  item:
    item-model:
    material: