"item:bus":
  model:
    item-model: minecraft:diamond_ore
  sounds:
    break:
      name:
      volume:
      pitch:
    place:
      name:
      volume:
      pitch:
  meta:
    no_explosion: true
    hardness: 2
    blast_resistance: 1
    silk_touch: