item:bus:
  item-model: packetblocks:electrum_ore
  material: STONE
  display-name: Electrum Ore
  sounds:
    break:
      key: minecraft:block.amethyst_block.break
    place:
      key: minecraft:block.amethyst_block.break
  loot:
    - type: item
      key: minecraft:stone
      min: 1
      max: 2
      weight: 5
    - type: experience
      min: 1
      max: 2
      weight: 2

