name: ModularJobs
version: '1.1'
main: org.aincraft.PacketBlocks
authors: [ mintychochip ]
api-version: '1.13'
softdepend:
  - Preferences
commands:
  test:
    description: asdads
  item:
    description: test
