name: Release

on:
  push:
    tags: ['v*.*.*']  # e.g. v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Publish to Maven Central (Central Portal)
        run: |
          ./gradlew :pb-api:publishAllPublicationsToCentralPortal \
            -PmavenCentralUsername="${{ secrets.MAVEN_CENTRAL_USERNAME }}" \
            -PmavenCentralPassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}" \
            --no-daemon --stacktrace
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
